name: gnome-dictionary
adopt-info: gnome-dictionary
summary: Check word definitions and spellings in an online dictionary
description: |
  GNOME Dictionary is a simple dictionary application that looks up
  definitions of words online.

  Though it looks up English definitions by default, you can easily switch to
  Spanish or add other online dictionaries using the DICT protocol to suit your
  needs.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  gnome-dictionary:
    interface: dbus
    bus: session
    name: org.gnome.Dictionary

apps:
  gnome-dictionary:
    command: usr/bin/gnome-dictionary
    extensions: [gnome]
    plugs:
      - network
    desktop: usr/share/applications/org.gnome.Dictionary.desktop

parts:
  gnome-dictionary:
    source: https://gitlab.gnome.org/GNOME/gnome-dictionary.git
    source-type: git
    source-tag: '40.0'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '41'
#     no-9x-revisions: true
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.Dictionary.appdata.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      # Remove the meson.build line for erroring on redundant-declarations
      sed -i.bak -e '/.*-Werror=redundant-decls.*$/d' src/meson.build
      patch -p1 < $CRAFT_PROJECT_DIR/patches/01-adapt-to-newer-meson-syntax.diff
    override-build: |
      sed -i.bak -e 's|Icon=@application_id@$|Icon=${SNAP}/meta/gui/org.gnome.Dictionary.svg|g' $CRAFT_PART_SRC/data/org.gnome.Dictionary.desktop.in.in
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/scalable/org.gnome.Dictionary.svg $CRAFT_PART_INSTALL/meta/gui/
      craftctl default
